export const paths = {
  home: '/',
  signUp: '/auth/signup',
  signUpEmail: '/auth/signup/email',
  signIn: '/auth/signin',
  signOut: '/auth/signout',
  profile: '/profile',
  searchSeries: '/series/search',
  searchSeriesResults: '/series/search/results',
  searchMovies: '/movie/search',
  searchMoviesResults: '/movie/search/results',
  searchEpisodes: '/episode/search',
  searchEpisodesResults: '/episode/search/results',
  series: '/series',
  movie: '/movie',
  episode: '/episode',
};
